### PR TITLE
Zachary d sturtz/fxgl

### PR DESCRIPTION
**Pull request by ZacharyDSturtz**
Extracted hard-coded strings into .properties language files and provided references along with German translations. (Issue 446)

### CODE REVIEW

**Comment by AlmasB** [comment]
Please raise the PR against the development branch (0.5.2), as per [Contribution guide](https://github.com/AlmasB/FXGL/blob/master/CONTRIBUTING.md#workflow)

**Comment by ZacharyDSturtz** [comment]
So, aside from your explicitly requested changes, the checks for both Codacy and Travis CI come back positive, but for Codecov the report comes back negative. Why? Where do I see what changes need to be made to make them positive?

**Comment by AlmasB** [comment]
Don't worry about codecov, it's probably `newButton()` not being covered

**Comment by AlmasB** [comment]
I've also updated base for pull request to 0.5.2

**Comment by ZacharyDSturtz** [comment]
Alright. I also removed the accidental log.* translations along with the author/powered by translations.

**Comment by ZacharyDSturtz** [comment]
So, are there any other changes that I need to implement?

**Comment by AlmasB** [comment]
For the future, please branch away from the development branch and not master branch, to avoid potential merging issues.

Just let me know once you've finalized your changes and I'll review them.

**Comment by ZacharyDSturtz** [comment]
Codacy review is failing because Codacy is unable to analyze branch 0.5.2. I tried enabling analysis in my Codacy project settings, but I'm still receiving the same issue. How should I fix this?

**Pull request merged**
