### PR TITLE
add apply LinearImpulse / Force / ForceToCenter / AngularImpulse / Torque methods to PhysicsComponent

### PR DESCRIPTION
**Pull request by pierredavidbelanger**
Some methods I am using in my project

### CODE REVIEW

**Comment by pierredavidbelanger** [comment]
I am not sur all the physics math are correct, since the forces are usually based on Newton metre and I am using [toMeters](https://github.com/AlmasB/FXGL/blob/master/src/main/java/com/almasb/fxgl/physics/PhysicsWorld.java#L580) to convert pixel to N-m ... but it works :)

**Comment by AlmasB** [comment]
Yeah, technically it should, since there's a 1:1 correlation. Do you have any screenshots I could use for [showcase](https://github.com/AlmasB/FXGL/wiki/Sample-Projects)?

**Comment by pierredavidbelanger** [comment]
Its only a toy project where agents evolve in a physic 2d world.
Their decisions (movement, attack, breed) are made using neural network.
When they breed, they produce new agents with a new neural network  evolved using the [NEAT](http://nn.cs.utexas.edu/?neat) algorithm.

I am more concern about the NeuralNet part than the visual part, so for now it looks like boring colored squares running everywhere on a boring white background :)

So, no screenshot so far, I will let you know when (if) I have some decent one to show.

Thank you!

**Comment by AlmasB** [comment]
Sounds awesome! Let me know what kind of support you need from FXGL. Though it seems jbox2d is the most important aspect in your case.

**Pull request merged**
