### PR TITLE
New language and issue

### PR DESCRIPTION
**Pull request by Valdar-Soft**
Specific style classes (492) and Hungarian language support.

### CODE REVIEW

**Comment by AlmasB** [comment]
the original looks good, what was the reason for reopen?

**Comment by Valdar-Soft** [comment]
I tried to resolve these errors. But I see that was Codacy - was not enabled on 0.4.3.

**Comment by AlmasB** [comment]
Yeah, don't worry about codacy or codecov, as long as travis passes I'm happy

**Comment by AlmasB** [comment]
Let me know when you want to merge this, I'm happy with the changes

**Comment by Valdar-Soft** [comment]
I think you can merge this one :) 
I am solving another issue right now :)

**Comment by AlmasB** [comment]
Ye, I'm just figuring out how to make FXGLScrollPane use FXGLScrollBar style since JavaFX does it internally. If I can't find a clean solution to this, I'll just ditch the fxgl scroll bar. As for the rest, a very good PR, thanks!

**Comment by AlmasB** [comment]
I've got it. It's `.fxgl-scroll-pane .scroll-bar` since scroll bar is fixed to a scroll pane (almost) we can style it this way, so there is no need for specific fxgl scroll bars (not yet anyway). I'll be closing #492 shortly

**Pull request merged**
