### PR TITLE
feat: added a particle callback function that will be executed when the particle is removed

### PR DESCRIPTION
**Pull request by NexaCore168**
I think this function is still necessary.

### CODE REVIEW

**Comment by AlmasB** [comment]
Hi, thanks for this. Please can you provide a use case example.

**Comment by NexaCore168** [comment]
> Hi, thanks for this. Please can you provide a use case example.

https://www.bilibili.com/video/BV1iz4y1s7WW/?spm_id_from=333.337.search-card.all.click&vd_source=33227c9937f8f5c6629d4a8cb0e5be97
The URL above is a small demo. The raindrops in the video are simulated using a particle system. When raindrops fall onto the surface of the lake, they can cause ripples.

**Comment by DeathPhoenix22** [comment]
Hi,
I was thinking of doing this! If it gets in the Engine, thanks for it :)

**Comment by AlmasB** [comment]
@wonderfulLand Thanks for clarifying. I've just made a few editorial changes to maintain consistency. It's all merged now.

**Pull request merged**
